const ActionType = {
    ACCOUNT_DETAIL: 'ACCOUNT_DETAIL',
    BOUNTY_TASKS: 'BOUNTY_TASKS',
    BOUNTY_TASK: 'BOUNTY_TASK',
    BOUNTY_CLAIMS: 'BOUNTY_CLAIMS',
    ADMIN_PENDING_BOUNTY_CLAIMS: 'ADMIN_PENDING_BOUNTY_CLAIMS',
};

export default ActionType;
